repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [python]
        additional_dependencies:
          - flake8-annotations
          - flake8-docstrings
      - id: flake8
        name: flake8-docstrings (warn)
        types: [python]
        args: ["--select=D", "--exit-zero"]
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        types: [python]
        pass_filenames: false
        args: ["--config-file", "setup.cfg", "."]
        additional_dependencies:
          - types-PyMySQL
          - types-requests
